<?php

namespace App\Domains\Intelligence\Services;

use App\Domains\Intelligence\Contracts\IntelligenceProviderContract;
use App\Domains\Intelligence\DTOs\AgentExecutionResponse;
use App\Domains\Intelligence\Models\Agent;

class NullIntelligenceProvider implements IntelligenceProviderContract
{
    public function respond(Agent $agent, array $payload): AgentExecutionResponse
    {
        $content = trim(implode("\n\n", array_filter([
            'Provider-neutral stub response generated by the POA Intelligence Engine.',
            'Agent: '.$agent->name,
            filled($payload['user_message'] ?? null) ? 'User message: '.$payload['user_message'] : null,
            ! empty($payload['memory']) ? 'Memory considered: '.count($payload['memory']).' record(s).' : null,
            ! empty($payload['tool_outputs']) ? 'Tool outputs attached: '.count($payload['tool_outputs']).'.' : null,
        ])));

        return new AgentExecutionResponse(
            $content,
            (string) ($payload['provider'] ?? 'stub'),
            (string) ($payload['model'] ?? 'stub-chat-v1'),
            [
                'prompt_tokens' => str($content)->length(),
                'completion_tokens' => max((int) ceil(str_word_count($content) / 1.3), 1),
                'total_tokens' => str($content)->length() + max((int) ceil(str_word_count($content) / 1.3), 1),
            ],
            $payload['tool_outputs'] ?? [],
            $payload['memory'] ?? [],
            [
                'stubbed' => true,
            ],
        );
    }
}
