import { CirclePlus } from "lucide-react";

export const ComplianceRecordModelFormConfig = {
  title: "Compliance Record Form",
  description: "Track statutory, governance, and reporting obligations against registered organisations.",
  addButton: {
    id: "add-compliance-record-button",
    label: "Add Compliance Record",
    className: "rounded-lg bg-red-600 px-4 py-2 text-white hover:bg-red-700",
    icon: CirclePlus,
    type: "button",
    variant: "default",
  },
  fields: [
    {
      id: "compliance-organisation",
      name: "organisation_id",
      label: "Organisation",
      type: "select",
      required: true,
      optionsSource: "organisations",
      optionLabel: "name",
      optionValue: "id",
    },
    {
      id: "compliance-title",
      name: "title",
      label: "Record Title",
      type: "text",
      required: true,
      autoFocus: true,
    },
    {
      id: "compliance-area",
      name: "compliance_area",
      label: "Compliance Area",
      type: "select",
      required: true,
      options: [
        { label: "CIPC", value: "CIPC" },
        { label: "NPO Directorate", value: "NPO Directorate" },
        { label: "SARS", value: "SARS" },
        { label: "PBO", value: "PBO" },
        { label: "Board Governance", value: "Board Governance" },
        { label: "Funding Reporting", value: "Funding Reporting" },
      ],
    },
    {
      id: "compliance-status",
      name: "status",
      label: "Status",
      type: "select",
      required: true,
      options: [
        { label: "Planned", value: "planned" },
        { label: "In Progress", value: "in_progress" },
        { label: "Submitted", value: "submitted" },
        { label: "Approved", value: "approved" },
        { label: "Overdue", value: "overdue" },
      ],
    },
    {
      id: "compliance-reference-code",
      name: "reference_code",
      label: "Reference Code",
      type: "text",
    },
    {
      id: "compliance-filing-frequency",
      name: "filing_frequency",
      label: "Filing Frequency",
      type: "select",
      options: [
        { label: "Monthly", value: "monthly" },
        { label: "Quarterly", value: "quarterly" },
        { label: "Biannual", value: "biannual" },
        { label: "Annual", value: "annual" },
        { label: "Ad Hoc", value: "ad_hoc" },
      ],
    },
    {
      id: "compliance-due-date",
      name: "due_date",
      label: "Due Date",
      type: "date",
    },
    {
      id: "compliance-submitted-at",
      name: "submitted_at",
      label: "Submitted At",
      type: "date",
    },
    {
      id: "compliance-owner-name",
      name: "owner_name",
      label: "Responsible Owner",
      type: "text",
    },
    {
      id: "compliance-notes",
      name: "notes",
      label: "Notes",
      type: "textarea",
    },
  ],
};
