import { CirclePlus } from "lucide-react";

export const ProgramModelFormConfig = {
  moduleTitle: "Programs",
  title: "Program Form",
  description: "Fill in the details to add or edit a program.",

  addButton: {
    id: "add-program-button",
    label: "Add Program",
    className: "rounded-lg bg-red-600 px-4 py-2 text-white hover:bg-red-700",
    icon: CirclePlus,
    type: "button",
    variant: "default",
  },

  fields: [
    {
      id: "program-title",
      name: "title",
      label: "Programme Name",
      type: "text",
      placeholder: "Enter programme name",
      autoFocus: true,
      required: true,
    },
    {
      id: "program-code",
      name: "code",
      label: "Programme Code",
      type: "text",
      placeholder: "POA-001",
    },
    {
      id: "program-description",
      name: "description",
      label: "Description",
      type: "textarea",
      rows: 3,
      placeholder: "Enter description",
      required: true,
    },
    {
      id: "program-strategic-objective",
      name: "strategic_objective",
      label: "Strategic Objective",
      type: "textarea",
      rows: 3,
      placeholder: "Capture the strategic objective for this programme",
    },
    {
      id: "program-start-date",
      name: "start_date",
      label: "Start Date",
      type: "date",
    },
    {
      id: "program-end-date",
      name: "end_date",
      label: "End Date",
      type: "date",
    },
    {
      id: "program-status",
      name: "status",
      label: "Status",
      type: "select",
      required: true,
      options: [
        { label: "Draft", value: "draft" },
        { label: "Planned", value: "planned" },
        { label: "Active", value: "active" },
        { label: "Suspended", value: "suspended" },
        { label: "Completed", value: "completed" },
        { label: "Cancelled", value: "cancelled" },
      ],
    },
    {
      id: "program-budget",
      name: "budget",
      label: "Budget",
      type: "number",
      placeholder: "0.00",
      min: 0,
    },
    {
      id: "program-funding-source",
      name: "funding_source",
      label: "Funding Source",
      type: "text",
      placeholder: "Government grant, donor, private sector",
    },
    {
      id: "program-committee",
      name: "responsible_committee_id",
      label: "Responsible Committee",
      type: "select",
      optionsSource: "committees",
      optionLabel: "name",
      optionValue: "id",
    },
    {
      id: "program-manager",
      name: "programme_manager_id",
      label: "Programme Manager",
      type: "select",
      optionsSource: "staffMembers",
      optionLabel: "name",
      optionValue: "id",
    },
    {
      id: "program-slug",
      name: "slug",
      label: "Slug",
      type: "text",
      placeholder: "Optional slug",
    },
  ],
};
