import { CirclePlus } from "lucide-react";

export const ProjectModelFormConfig = {
  moduleTitle: "Projects",
  title: "Project Form",
  description: "Fill in the details to add or edit a project.",

  addButton: {
    id: "add-project-button",
    label: "Add Project",
    className: "rounded-lg bg-red-600 px-4 py-2 text-white hover:bg-red-700",
    icon: CirclePlus,
    type: "button",
    variant: "default",
  },

  fields: [
    {
      id: "project-name",
      name: "name",
      label: "Project Name",
      type: "text",
      placeholder: "Enter project name",
      autoFocus: true,
      required: true,
    },
    {
      id: "project-start-date",
      name: "start_date",
      label: "Start Date",
      type: "date",
      required: true,
    },
    {
      id: "project-end-date",
      name: "end_date",
      label: "End Date",
      type: "date",
    },
    {
      id: "project-status",
      name: "status",
      label: "Status",
      type: "select",
      required: true,
      options: [
        { label: "Planned", value: "planned" },
        { label: "Active", value: "active" },
        { label: "Completed", value: "completed" },
        { label: "On Hold", value: "on_hold" },
        { label: "Cancelled", value: "cancelled" },
      ],
    },
    {
      id: "project-program",
      name: "program_id",
      label: "Program",
      type: "select",
      optionsSource: "programs",
      optionLabel: "title",
      optionValue: "id",
      required: true,
    },
    {
      id: "project-sponsor",
      name: "sponsor_stakeholder_id",
      label: "Sponsor (Stakeholder)",
      type: "select",
      optionsSource: "stakeholders",
      optionLabel: "name",
      optionValue: "id",
    },
    {
      id: "project-partners",
      name: "partner_stakeholder_ids",
      label: "Implementation Partners",
      type: "select",
      optionsSource: "partnerStakeholders",
      optionLabel: "name",
      optionValue: "id",
      multiple: true,
    },
    {
      id: "project-manager",
      name: "project_manager_id",
      label: "Project Manager",
      type: "select",
      optionsSource: "staffMembers",
      optionLabel: "name",
      optionValue: "id",
      required: true,
    },
    {
      id: "project-contract-reference",
      name: "contract_reference",
      label: "Contract Reference",
      type: "text",
      placeholder: "Enter contract or funding reference",
    },
    {
      id: "project-funding-amount",
      name: "funding_amount",
      label: "Funding Amount",
      type: "number",
      placeholder: "0.00",
      min: 0,
    },
    {
      id: "project-reporting-cadence",
      name: "reporting_cadence",
      label: "Reporting Cadence",
      type: "select",
      options: [
        { label: "Monthly", value: "monthly" },
        { label: "Quarterly", value: "quarterly" },
        { label: "Biannual", value: "biannual" },
        { label: "Annual", value: "annual" },
        { label: "Ad Hoc", value: "ad_hoc" },
      ],
    },
    {
      id: "project-reporting-obligations",
      name: "reporting_obligations",
      label: "Reporting Obligations",
      type: "textarea",
      placeholder: "Capture sponsor or partner reporting obligations.",
    },
    {
      id: "project-description",
      name: "description",
      label: "Description",
      type: "textarea",
      placeholder: "Enter description",
    },
  ],
};
