import { CirclePlus } from "lucide-react";

export const ResolutionModelFormConfig = {
  description: "Track board and committee resolutions through execution.",
  addButton: {
    id: "add-resolution-button",
    label: "Add Resolution",
    className: "rounded-lg bg-red-600 px-4 py-2 text-white hover:bg-red-700",
    icon: CirclePlus,
    type: "button",
    variant: "default",
  },
  fields: [
    {
      id: "resolution-organisation-id",
      name: "organisation_id",
      label: "Organisation",
      type: "select",
      required: true,
      optionsSource: "organisations",
      optionLabel: "name",
      optionValue: "id",
    },
    {
      id: "resolution-meeting-id",
      name: "meeting_id",
      label: "Meeting",
      type: "select",
      required: true,
      optionsSource: "meetings",
      optionLabel: "name",
      optionValue: "id",
    },
    {
      id: "resolution-owner-id",
      name: "owner_id",
      label: "Owner",
      type: "select",
      optionsSource: "users",
      optionLabel: "name",
      optionValue: "id",
    },
    {
      id: "resolution-number",
      name: "resolution_number",
      label: "Resolution Number",
      type: "text",
      required: true,
      autoFocus: true,
    },
    {
      id: "resolution-title",
      name: "title",
      label: "Title",
      type: "text",
      required: true,
    },
    {
      id: "resolution-due-date",
      name: "due_date",
      label: "Due Date",
      type: "date",
    },
    {
      id: "resolution-status",
      name: "status",
      label: "Status",
      type: "select",
      required: true,
      options: [
        { label: "Open", value: "open" },
        { label: "In Progress", value: "in_progress" },
        { label: "Completed", value: "completed" },
        { label: "Overdue", value: "overdue" },
      ],
    },
    {
      id: "resolution-description",
      name: "description",
      label: "Description",
      type: "textarea",
    },
  ],
};
